# Generated by Django 3.2.13 on 2022-11-06 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('menupan', models.TextField()),
                ('category', models.IntegerField(choices=[(1, '한식'), (2, '중식'), (3, '프렌치'), (4, '이탈리안'), (5, '스페니쉬'), (6, '아메리칸'), (7, '튀르키예'), (8, '디저트'), (9, '멕시칸'), (10, '최준홍님 pick!'), (11, '일식')], default=10)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/restaurant/')),
                ('thumbnail', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/restaurant/')),
                ('like_users', models.ManyToManyField(related_name='like_restaurants', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
