# Generated by Django 3.2.13 on 2022-11-03 01:18

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_remove_restaurant_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/restaurant/'),
        ),
    ]
