# Generated by Django 3.2.13 on 2022-11-03 01:19

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='images/restaurant/'),
        ),
    ]
