# Generated by Django 3.2.13 on 2022-11-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_restaurant_like_users'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurants',
        ),
    ]
