# Generated by Django 3.2.13 on 2022-11-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurant_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='restaurant',
            table=None,
        ),
    ]
