# Generated by Django 3.2.13 on 2022-11-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_restaurant_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='like_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
