# Generated by Django 3.2.13 on 2022-11-05 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_restaurant_like_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='like_cnt',
        ),
    ]
