# Generated by Django 3.2.13 on 2022-11-05 14:35

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_remove_restaurant_like_cnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/restaurant/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='images/restaurant/'),
        ),
    ]
