# Generated by Django 3.2.13 on 2022-11-02 12:05

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/reviews_file/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/reviews_file/'),
        ),
    ]
