# Generated by Django 3.2.13 on 2022-11-04 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_restaurant_table'),
        ('reviews', '0007_auto_20221103_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='restaurants.restaurant'),
        ),
    ]
