# Generated by Django 3.2.13 on 2022-11-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_remove_comment_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
